version: 2
updates:
  - package-ecosystem: pip
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Nekokatt"
    reviewers:
      - "Nekokatt"
      - "Tandemdude"
      - "Davfsa"
    rebase-strategy: auto
    target-branch: master
