stages:
  - test
  - deploy
  - webhooks

cache: pip

_test_job: &test_job
  install:
    - ${PYTHON_COMMAND} -m pip install nox
  before_script:
    - mkdir public > /dev/null 2>&1 || true
    - ${PYTHON_COMMAND} -V
  script:
    - ${PYTHON_COMMAND} -m nox --sessions pytest
    - bash <(curl -s https://codecov.io/bash)

_windows_test_job: &windows_test_job
  os: windows
  language: shell
  before_install:
    - choco install --no-progress python --version=${PYTHON_VERSION} -y
  env:
    - PYTHON_COMMAND="py -3"
  <<: *test_job

_linux_test_job: &linux_test_job
  os: linux
  language: python
  env:
    - PYTHON_COMMAND=python
  <<: *test_job

jobs:
  include:
    # Linting
    - name: "Linting"
      language: python
      python: "3.8.5"
      os: linux
      arch: amd64
      install: "pip install nox"
      stage: test
      script:
        - python -m nox --sessions safety mypy flake8

    - name: "Twemoji Mapping Verification"
      language: python
      python: "3.8.5"
      os: linux
      arch: amd64
      install: "pip install nox"
      stage: test
      script:
        - python -m nox --sessions twemoji-test

    - name: "Windows 10 Python 3.8.5 AMD64 Tests"
      env: PYTHON_VERSION="3.8.5"
      arch: amd64
      stage: test
      <<: *windows_test_job

    - name: "Windows 10 Python 3.9 Dev AMD64 Tests"
      env: PYTHON_VERSION="3.9.0-rc1 --pre"
      arch: amd64
      stage: test
      <<: *windows_test_job

    - name: "Linux Python 3.8.5 AMD64 Tests"
      python: "3.8.5"
      arch: amd64
      stage: test
      <<: *linux_test_job

    - name: "Linux Python 3.9 Dev AMD64 Tests"
      python: "3.9-dev"
      arch: amd64
      stage: test
      <<: *linux_test_job

    - name: "Linux Python 3.8.5 ARM64 Tests"
      python: "3.8.5"
      arch: arm64
      stage: test
      <<: *linux_test_job

    - name: "Linux Python 3.9 Dev ARM64 Tests"
      python: "3.9-dev"
      arch: arm64
      stage: test
      <<: *linux_test_job

    - name: "Deploy new release"
      if: tag IS present AND tag =~ /^\d+\.\d+\.\d+(\..*)?$/
      stage: deploy
      language: python
      python: "3.8.5"
      arch: amd64
      os: linux
      script:
        - bash scripts/deploy.sh
      env:
        secure: "J/lejouS7Usm5iup1IkEoNpzx3wWbx5le1nbKbZzFam4GlZmJBONwAVtTkvjKgWMUsLLtX+mahGY8eq3aJ7PjqZ/QnCN45eYaXhI04VIyPJDijbZ3CedU7gqEfjbE0P2Ib3HDsRB+CmEE5DPrulB3kWfLqZRDf7IV3X6Winmd2BMmGUm1yU4FO1dfLVfxI/DtSlaH+jnXbu7+HhJ0JsSdDoJL2ok/fAxOy6zS5uNh5ux8UVqVADaxpiGo7PLHSGGgx9QWx0jk0W7hesPqf07Ih2jb5bTKh0wOzPoYbw4nbHTCSkR8JDI/RGkk2rae3YtvU0655r4j3D3xNYak9jMLOvcywhxtDZwNwpmwpnW7IixPGgS4WMaEKCzyBTjv2hh6Xh8+lEIlE0jr+vPkkmlrhxZOgFQR88GcNnRfF+zC6oj6lF4tWPnRbFPEjpfwHQufnZ7JrHYve9rpMdalHjjr94hEXucKvOgEdvTQTqgar3/EqZJdjyyAKs0/WoRfUX370LcYvu6nb9v9ETLbFMo68TBY46E4jfG4hArC9rfwDmqZncTwg38GsLdzLfsTG9HvLg0U5TW508jCVN65Xdbzd3PmiYkcp40NbhmvQ6sFP3dc4rMiA0vFw5mPUzHYDxRpSYFSv9h2pVXvIEeNYRnSfpDocNOSXZFLkIQVL0xAyo="
